### ISSUE TITLE
TracingUtils.buildChildSpan creates a noop span, when trace-id is not in headers

### ISSUE THREAD

**Issue by dev-konrad** [opentracing-contrib/java-rabbitmq-client#18]
Hi,

I have been using your library for some time already - it behaves really nice and saved me a lot of coding - thanks! I do have one question / issue with it though. It relates to handleDelivery in TracingConsumer.

**Context:**

My application is a set of interconnected microservices and an initial call comes typically from integrations tests in python, or another java client.
Point is, in both of these situations, the client doesn't create a span himself. This is for a reason, we don't want to complicate things for them - they just want to execute a request and that's fine.
Instead, first span (trace) is created on the side of application, precisely in the first service that is hit with a request. And this is where the issue happens.

**Issue:**

In handleDelivery, there is a:
`Span child = TracingUtils.buildChildSpan(properties, queue, tracer);`
This tries to locate a trace in headers, but since it is a first service in chain of calls, it won't be there.
So, a noop span will be created instead of a normal one, representing 'receive' operation.
And since it is a noop span, it won't be a part of the whole trace, because the next span I'm creating in my code, can't reference (be a child) of a noop span.

**Possible solutions:**

Currently can't think of anything other than creating a span on the client side, but really don't wanna go this way. Alternative is, to modify TracingUtils.buildChildSpan and there, on *some* conditions create a regular span, when trace-id is not in headers. Don't know though if this is the right way to go.

Do you have any suggestions?
It's not a severe issue, but I reckon it's nice to have a full picture of how long the call is served.

Thanks!
Konrad

**Comment by malafeev** [comment]
thanks @mruki 
I submitted PR #19  to fix your issue

**Comment by malafeev** [comment]
fixed and released version 0.1.10

**Comment by dev-konrad** [comment]
thanks so much Sergei for fixing and releasing it so quickly! I have managed to test it and result is OK - I can now see the first 'receive' span.

BR,
Konrad
